# Application settings for NPC-in-a-game
# Put custom keys here. Example:
key1=HelloFromProperties
OPENAI_API_KEY=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
# npc.name=NPC-Default
# npc.spawnRate=0.25
